import{BLOCKS}from"./data.js";
export const SIZES={small:[64,28],medium:[96,36],large:[140,44]};
export function hashSeed(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hashSeed(seed);return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export function createWorld({name,seed,mode,preset,size}){const [w,h]=SIZES[size]||SIZES.medium;const world=generate(seed,w,h,preset);const now=Date.now();const spawn=findSpawn(world,w,h);return{id:crypto.randomUUID(),name:name||"My World",seed,mode,preset,size,width:w,height:h,world,inventory:{},hotbar:["soil","stone","wood","sand",null,null,null,null,null],activeTool:"shovel",activeBlock:null,selectedHotbar:0,tier:1,xp:0,dayPhase:.18,player:{x:spawn.x,y:spawn.y,vx:0,vy:0},chests:{},stats:{mined:0,placed:0,crafted:0,smelted:0,playSeconds:0},achievements:{},createdAt:now,updatedAt:now}}
function findSpawn(world,w,h){for(let x=3;x<Math.min(w-3,Math.max(18,Math.floor(w*.35)));x++){for(let y=3;y<h-2;y++){const here=world[y*w+x],up1=world[(y-1)*w+x],up2=world[(y-2)*w+x];if((here==="grass"||here==="soil"||here==="stone")&&up1==="sky"&&up2==="sky")return{x:x+.15,y:y-1.05}}}return{x:3.15,y:3}}
export function generate(seed,w,h,preset="normal"){const r=rng(seed),a=Array(w*h).fill("sky"),I=(x,y)=>y*w+x,heights=[];let s=preset==="flat"?Math.floor(h*.42):Math.floor(h*.38);
for(let x=0;x<w;x++){if(preset!=="flat"){s+=r()<.32?(r()<.5?-1:1):0;s=Math.max(7,Math.min(Math.floor(h*.55),s))}heights.push(s);for(let y=s;y<h;y++){let t=y===h-1?"bedrock":y===s?"grass":y<s+4?"soil":"stone";if(preset==="cave"&&y>s+2&&r()<.22)t="sky";else if(t==="stone"){const q=r();if(q<.025)t="diamond";else if(q<.07)t="gold";else if(q<.13)t="iron";else if(q<.24)t="coal"}a[I(x,y)]=t}}
if(preset!=="flat")for(let c=0;c<Math.max(8,Math.floor(w/8));c++){const cx=Math.floor(r()*w),cy=Math.floor(h*.55)+Math.floor(r()*Math.max(3,h*.25)),rad=1+Math.floor(r()*3);for(let y=cy-rad;y<=cy+rad;y++)for(let x=cx-rad;x<=cx+rad;x++)if(x>=0&&x<w&&y>=0&&y<h-1&&Math.hypot(x-cx,y-cy)<=rad+.2)a[I(x,y)]="sky"}
for(let x=3;x<w-3;x++)if(r()<.09&&preset!=="cave"){const y=heights[x],tr=2+Math.floor(r()*3);for(let t=1;t<=tr;t++)if(y-t>=0)a[I(x,y-t)]="wood";const top=y-tr;for(let oy=-2;oy<=1;oy++)for(let ox=-2;ox<=2;ox++)if(Math.abs(ox)+Math.abs(oy)<=3&&a[I(x+ox,top+oy)]==="sky")a[I(x+ox,top+oy)]="leaves"}
if(preset==="sky"){for(let i=0;i<a.length;i++)a[i]="sky";for(let x=3;x<Math.min(w,24);x++)for(let y=Math.floor(h*.52);y<Math.floor(h*.52)+3;y++)a[I(x,y)]=y===Math.floor(h*.52)?"grass":"soil";for(let x=0;x<w;x++)a[I(x,h-1)]="bedrock"}
return a}